package throw_Exception;

public class call_password3 extends Password3 {//using inhertiance for use the property of password3 class(parents class)....
public static void main(String args[]) {//create mainn method ...
	call_password3 obj=new call_password3();//create object of same class....
	obj.accept();//call the accept method.....
}
}
